# -*- coding: utf-8 -*-
"""Translated copy for the CleanMenuBar site.

Kept apart from the generator so a translator can work here without reading any
HTML. Every language carries the same keys; build-site.py fails loudly if one
is missing rather than silently emitting English.

Generated and rewritten programmatically — keep the structure uniform so it
stays safe to edit by script.
"""

LANGUAGES = [
    ('pt-BR', 'Português do Brasil', None),        # None = published at the site root
    ('en', 'English', 'en'),
    ('es', 'Español', 'es'),
    ('fr', 'Français', 'fr'),
    ('de', 'Deutsch', 'de'),
    ('ja', '日本語', 'ja'),
    ('zh-Hans', '简体中文', 'zh-hans'),
    ('zh-Hant', '繁體中文', 'zh-hant'),
    ('ru', 'Русский', 'ru'),
]

UPDATED = '2026-09-15'

C = {}

C['en'] = {
  'title': 'CleanMenuBar — hide menu bar icons on macOS 27',
  'description': 'CleanMenuBar hides your macOS menu bar icons. Open source, free, collects nothing. Built for macOS 27, the release that broke the others.',
  'tagline': "Hide the menu bar icons you don't want to look at.",
  'download': 'Download for macOS',
  'requirements': 'Free and open source · macOS 26 or later · Apple Silicon and Intel',
  'why_h': 'Why it exists',
  'why_1': 'macOS 27 rebuilt the menu bar as a single window and broke Hidden Bar, the app I used to hide icons. It relied on a technique that stopped working.',
  'why_2': 'CleanMenuBar is derived from Hidden Bar with an adapted mechanism, built and measured directly on macOS 27 Golden Gate one day after its public release (14 September 2026).',
  'what_h': 'What it does',
  'f1_t': 'Hide and reveal',
  'f1_d': 'A click, a global shortcut, or just hovering.',
  'f2_t': 'Always-hidden section',
  'f2_d': 'A second span that stays hidden even when you expand.',
  'f3_t': 'Auto-collapse',
  'f3_d': 'After 5, 10, 15, 30 or 60 seconds.',
  'f4_t': 'No permissions',
  'f4_d': 'No Accessibility, no Screen Recording. Runs sandboxed.',
  'f5_t': 'Nine languages',
  'f5_d': 'English, Portuguese, Spanish, French, German, Japanese, Chinese, Russian.',
  'f6_t': 'Collects nothing',
  'f6_d': 'No network, no telemetry, no accounts.',
  'how_h': 'Setting up',
  's1': 'Hold <kbd>⌘</kbd> and drag the icons you want hidden so they sit to the <strong>left</strong> of the CleanMenuBar separator.',
  's2': 'Anything to the <strong>right</strong> of the separator stays visible at all times.',
  's3': 'Click the arrow to collapse or expand, or press <kbd>⌃⌥⌘C</kbd> from anywhere.',
  's4': 'Once arranged, turn on <strong>Hide the separators</strong> to leave only the arrow.',
  'how_note': 'Positions survive relaunching — macOS remembers where each icon sits.',
  'install_h': 'Installing',
  'install_1': 'Download the <code>.dmg</code>, drag CleanMenuBar to Applications, and open it.',
  'install_note': 'The app is signed with a Developer ID and notarised by Apple, so it opens without warnings. Until it reaches the Mac App Store, the download above is the official way to get it.',
  'nav_home': 'Home',
  'nav_privacy': 'Privacy',
  'nav_terms': 'Terms of Use',
  'licence_short': 'MIT License',
  'pp_title': 'Privacy Policy',
  'pp_meta': 'CleanMenuBar · Updated {date} · Applies to all versions',
  'pp_short_h': 'The short version',
  'pp_short_1': 'CleanMenuBar collects nothing, sends nothing, and has no servers.',
  'pp_short_note': "That is not a policy choice that could quietly change — it is what the app is technically capable of. It runs inside Apple's App Sandbox <strong>with no network entitlement</strong>, so it could not open a network connection even if its code tried to.",
  'pp_store_h': 'What the app stores',
  'pp_store_1': "Your settings — the language, the shortcut, whether auto-collapse is on and after how long — are written to macOS's standard preferences store, inside the app's own sandbox container:",
  'pp_store_2': 'This stays on your Mac. It is not transmitted, not backed up by us, and not readable by us. Deleting the app and that folder removes everything CleanMenuBar has ever written.',
  'pp_store_3': "macOS separately remembers where you dragged your menu bar icons. That is the system's own record, not ours, and it lives outside the app.",
  'pp_not_h': 'What the app does not do',
  'pp_n1': 'No analytics, telemetry, crash reporting or usage statistics',
  'pp_n2': 'No accounts, logins or identifiers',
  'pp_n3': 'No advertising, and no data shared with anyone',
  'pp_n4': 'No network requests of any kind',
  'pp_n5': 'No access to your files, contacts, camera, microphone or location',
  'pp_perm_h': 'Permissions',
  'pp_perm_1': 'CleanMenuBar requests <strong>no</strong> special permissions. It needs neither Accessibility nor Screen Recording, which sets it apart from most menu bar tools — the global shortcut uses an API that works without them, and the app never reads the screen.',
  'pp_perm_2': "If macOS ever prompts you for a permission on CleanMenuBar's behalf, treat that as a bug and report it.",
  'pp_kids_h': 'Children',
  'pp_kids_1': 'CleanMenuBar is not directed at children and collects no data from anyone, regardless of age.',
  'pp_src_h': 'The source is public',
  'pp_src_1': 'You do not have to take any of this on trust. The complete source is published under the MIT Licence, including the entitlements file that declares what the app is allowed to do.',
  'pp_chg_h': 'Changes',
  'pp_chg_1': 'If this policy ever changes, the revised version will be published here with a new date. Since the app collects nothing, any change that mattered would require a new release — and the source diff would show it.',
  'contact_h': 'Contact',
  'tu_title': 'Terms of Use',
  'tu_meta': 'CleanMenuBar · Updated {date}',
  'tu_who_h': '1. Who provides the software',
  'tu_who_1': 'CleanMenuBar is provided by <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>, contact <a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>.',
  'tu_lic_h': '2. Licence',
  'tu_lic_1': 'CleanMenuBar is free software distributed under the <strong>MIT Licence</strong>. You may use, copy, modify, distribute and even sell it, free of charge, provided you keep the copyright notice and licence text in all copies.',
  'tu_lic_2': 'The full text travels with every copy of the app, reachable at <strong>About → Licenses</strong>.',
  'tu_lic_3': 'CleanMenuBar derives from <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a> by Dwarves Foundation, also under the MIT Licence. Their copyright notice ships with the app.',
  'tu_war_h': '3. No warranty',
  'tu_war_1': 'The software is provided <strong>“as is”</strong>, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and non-infringement.',
  'tu_war_2': 'We do not warrant that the app will run uninterrupted or error-free, or that it will be compatible with any particular hardware configuration, macOS version, or combination of other software.',
  'tu_lia_h': '4. Limitation of liability',
  'tu_lia_1': 'To the maximum extent permitted by applicable law, the authors and copyright holders shall not be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from or in connection with the software or its use.',
  'tu_lia_2': 'This includes, without limitation, loss of data, lost profits, business interruption, and indirect or incidental damages.',
  'tu_lia_3': 'Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable Brazilian law, including consumer protection legislation.',
  'tu_risk_h': '5. Use at your own risk',
  'tu_risk_1': "CleanMenuBar changes how icons are displayed in the macOS menu bar using only Apple's public APIs. Even so, menu bar behaviour can change between operating system versions, and macOS updates may affect how the app works.",
  'tu_risk_2': 'You are responsible for keeping backups of your data and for judging whether the software suits your use.',
  'tu_priv_h': '6. Privacy',
  'tu_priv_1': 'CleanMenuBar collects, transmits and remotely stores nothing.',
  'tu_chg_h': '7. Changes',
  'tu_chg_1': 'These Terms may be updated. The version in force is always the one published on this page, bearing the date shown above.',
  'tu_law_h': '8. Governing law',
  'tu_law_1': 'These Terms are governed by Brazilian law.',
}

C['pt-BR'] = {
  'title': 'CleanMenuBar — esconda ícones da barra de menus no macOS 27',
  'description': 'O CleanMenuBar esconde os ícones da barra de menus do macOS. Open-source, gratuito, não coleta nada. Feito para o macOS 27, a versão que quebrou os outros.',
  'tagline': 'Esconda os ícones da barra de menus que você não quer ver.',
  'download': 'Baixar para macOS',
  'requirements': 'Grátis e open-source · macOS 26 ou posterior · Apple Silicon e Intel',
  'why_h': 'Por que ele existe',
  'why_1': 'O macOS 27 reconstruiu a barra de menus como uma única janela e quebrou o Hidden Bar, app que eu utilizava e que escondia ícones. Ele usava uma técnica que passou a não funcionar mais.',
  'why_2': 'O CleanMenuBar é uma implementação derivada do Hidden Bar, com mecanismo adaptado, e foi criado e medido diretamente no macOS 27 Golden Gate um dia após o seu lançamento público (dia 14/09/2026).',
  'what_h': 'O que ele faz',
  'f1_t': 'Esconde e revela',
  'f1_d': 'Um clique, um atalho global ou o simples passar do cursor.',
  'f2_t': 'Seção sempre oculta',
  'f2_d': 'Um segundo trecho que permanece escondido mesmo ao expandir.',
  'f3_t': 'Recolhimento automático',
  'f3_d': 'Após 5, 10, 15, 30 ou 60 segundos.',
  'f4_t': 'Nenhuma permissão',
  'f4_d': 'Sem Acessibilidade, sem Gravação de Tela. Roda em sandbox.',
  'f5_t': 'Nove idiomas',
  'f5_d': 'Português, inglês, espanhol, francês, alemão, japonês, chinês e russo.',
  'f6_t': 'Não coleta nada',
  'f6_d': 'Sem rede, sem telemetria, sem contas.',
  'how_h': 'Como usar',
  's1': 'Segure <kbd>⌘</kbd> e arraste os ícones que quer esconder para a <strong>esquerda</strong> do separador do CleanMenuBar.',
  's2': 'O que ficar à <strong>direita</strong> do separador permanece sempre visível.',
  's3': 'Clique na seta para recolher ou expandir, ou pressione <kbd>⌃⌥⌘C</kbd> de qualquer lugar.',
  's4': 'Depois de organizar tudo, ative <strong>Ocultar os separadores</strong> para deixar só a seta.',
  'how_note': 'As posições sobrevivem a reinícios — o macOS lembra onde cada ícone ficou.',
  'install_h': 'Instalação',
  'install_1': 'Baixe o <code>.dmg</code>, arraste o CleanMenuBar para a pasta Aplicativos e abra.',
  'install_note': 'O app é assinado com Developer ID e notarizado pela Apple, então abre sem avisos. Enquanto não estiver na Mac App Store, o download acima é a forma oficial de obtê-lo.',
  'nav_home': 'Início',
  'nav_privacy': 'Privacidade',
  'nav_terms': 'Termos de Uso',
  'licence_short': 'Licença MIT',
  'pp_title': 'Política de Privacidade',
  'pp_meta': 'CleanMenuBar · Atualizado em {date} · Aplica-se a todas as versões',
  'pp_short_h': 'Resumo',
  'pp_short_1': 'O CleanMenuBar não coleta nada, não envia nada e não possui servidores.',
  'pp_short_note': 'Isso não é uma decisão de política que possa mudar silenciosamente — é o que o aplicativo é tecnicamente capaz de fazer. Ele roda dentro do App Sandbox da Apple <strong>sem permissão de rede</strong>, de modo que não conseguiria abrir uma conexão nem se o código tentasse.',
  'pp_store_h': 'O que fica armazenado',
  'pp_store_1': 'Suas preferências — idioma, atalho, se o recolhimento automático está ligado e após quanto tempo — são gravadas no armazenamento padrão de preferências do macOS, dentro do contêiner isolado do próprio aplicativo:',
  'pp_store_2': 'Isso permanece no seu Mac. Não é transmitido, não é copiado por nós e não é legível por nós. Apagar o aplicativo e essa pasta remove tudo o que o CleanMenuBar já escreveu.',
  'pp_store_3': 'Separadamente, o macOS lembra onde você arrastou os ícones da barra de menus. Esse é um registro do próprio sistema, não nosso, e fica fora do aplicativo.',
  'pp_not_h': 'O que o aplicativo não faz',
  'pp_n1': 'Sem análises, telemetria, relatórios de falha ou estatísticas de uso',
  'pp_n2': 'Sem contas, logins ou identificadores',
  'pp_n3': 'Sem publicidade e sem compartilhamento de dados com terceiros',
  'pp_n4': 'Sem requisições de rede de qualquer natureza',
  'pp_n5': 'Sem acesso a arquivos, contatos, câmera, microfone ou localização',
  'pp_perm_h': 'Permissões',
  'pp_perm_1': 'O CleanMenuBar não solicita <strong>nenhuma</strong> permissão especial. Não precisa de Acessibilidade nem de Gravação de Tela, o que o diferencia da maioria das ferramentas de barra de menus: o atalho global usa uma API que funciona sem elas, e o aplicativo nunca lê a tela.',
  'pp_perm_2': 'Se o macOS alguma vez solicitar uma permissão em nome do CleanMenuBar, trate isso como um defeito e nos avise.',
  'pp_kids_h': 'Crianças',
  'pp_kids_1': 'O CleanMenuBar não é direcionado a crianças e não coleta dados de ninguém, independentemente da idade.',
  'pp_src_h': 'O código é público',
  'pp_src_1': 'Você não precisa acreditar em nada disso. O código-fonte completo está publicado sob Licença MIT, incluindo o arquivo de entitlements que declara o que o aplicativo tem permissão de fazer.',
  'pp_chg_h': 'Alterações',
  'pp_chg_1': 'Se esta política mudar, a versão revisada será publicada nesta página com nova data. Como o aplicativo não coleta nada, qualquer mudança relevante exigiria uma nova versão — e a diferença no código-fonte a revelaria.',
  'contact_h': 'Contato',
  'tu_title': 'Termos de Uso',
  'tu_meta': 'CleanMenuBar · Atualizado em {date}',
  'tu_who_h': '1. Quem fornece o software',
  'tu_who_1': 'O CleanMenuBar é fornecido por <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>, contato <a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>.',
  'tu_lic_h': '2. Licença',
  'tu_lic_1': 'O CleanMenuBar é software livre, distribuído sob a <strong>Licença MIT</strong>. Você pode usá-lo, copiá-lo, modificá-lo, distribuí-lo e até vendê-lo, gratuitamente, desde que mantenha o aviso de direitos autorais e o texto da licença em todas as cópias.',
  'tu_lic_2': 'O texto completo acompanha cada cópia do aplicativo, acessível em <strong>Sobre → Licenças</strong>.',
  'tu_lic_3': 'O CleanMenuBar deriva do <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a>, da Dwarves Foundation, também sob Licença MIT. O aviso de copyright deles acompanha o aplicativo.',
  'tu_war_h': '3. Ausência de garantia',
  'tu_war_1': 'O software é fornecido <strong>“no estado em que se encontra”</strong>, sem garantia de qualquer natureza, expressa ou implícita, incluindo, sem limitação, garantias de comercialização, adequação a uma finalidade específica e não violação de direitos.',
  'tu_war_2': 'Não garantimos que o aplicativo funcionará sem interrupções ou erros, nem que será compatível com qualquer configuração específica de hardware, versão do macOS ou combinação de outros aplicativos.',
  'tu_lia_h': '4. Limitação de responsabilidade',
  'tu_lia_1': 'Na máxima extensão permitida pela legislação aplicável, os autores e detentores dos direitos autorais não serão responsáveis por qualquer reclamação, dano ou outra responsabilidade, seja em ação contratual, extracontratual ou de outra natureza, decorrente do software ou de seu uso.',
  'tu_lia_2': 'Isso abrange, sem limitação, perda de dados, lucros cessantes, interrupção de atividade e danos indiretos ou incidentais.',
  'tu_lia_3': 'Nada nestes Termos exclui ou limita responsabilidades que não possam ser excluídas ou limitadas pela legislação brasileira aplicável, inclusive pelo Código de Defesa do Consumidor.',
  'tu_risk_h': '5. Uso por sua conta e risco',
  'tu_risk_1': 'O CleanMenuBar altera a exibição de ícones na barra de menus do macOS utilizando exclusivamente APIs públicas da Apple. Ainda assim, o comportamento da barra de menus pode mudar entre versões do sistema operacional, e atualizações do macOS podem afetar o funcionamento do aplicativo.',
  'tu_risk_2': 'Você é responsável por manter cópias de segurança dos seus dados e por avaliar a adequação do software ao seu uso.',
  'tu_priv_h': '6. Privacidade',
  'tu_priv_1': 'O CleanMenuBar não coleta, transmite ou armazena remotamente qualquer dado.',
  'tu_chg_h': '7. Alterações',
  'tu_chg_1': 'Estes Termos podem ser atualizados. A versão vigente é sempre a publicada nesta página, com a data de atualização indicada acima.',
  'tu_law_h': '8. Legislação aplicável',
  'tu_law_1': 'Estes Termos são regidos pela legislação brasileira.',
}

C['es'] = {
  'title': 'CleanMenuBar — oculta iconos de la barra de menús en macOS 27',
  'description': 'CleanMenuBar oculta los iconos de la barra de menús de macOS. Código abierto, gratuito, no recopila nada.',
  'tagline': 'Oculta los iconos de la barra de menús que no quieres ver.',
  'download': 'Descargar para macOS',
  'requirements': 'Gratis y de código abierto · macOS 26 o posterior · Apple Silicon e Intel',
  'why_h': 'Por qué existe',
  'why_1': 'macOS 27 reconstruyó la barra de menús como una sola ventana y rompió Hidden Bar, la app que yo usaba para ocultar iconos. Se apoyaba en una técnica que dejó de funcionar.',
  'why_2': 'CleanMenuBar es una implementación derivada de Hidden Bar, con el mecanismo adaptado, creada y medida directamente en macOS 27 Golden Gate un día después de su lanzamiento público (14/09/2026).',
  'what_h': 'Qué hace',
  'f1_t': 'Oculta y muestra',
  'f1_d': 'Un clic, un atajo global o simplemente pasar el cursor.',
  'f2_t': 'Sección siempre oculta',
  'f2_d': 'Un segundo tramo que permanece oculto incluso al expandir.',
  'f3_t': 'Contracción automática',
  'f3_d': 'Tras 5, 10, 15, 30 o 60 segundos.',
  'f4_t': 'Ningún permiso',
  'f4_d': 'Sin Accesibilidad, sin Grabación de Pantalla. Se ejecuta aislada.',
  'f5_t': 'Nueve idiomas',
  'f5_d': 'Español, inglés, portugués, francés, alemán, japonés, chino y ruso.',
  'f6_t': 'No recopila nada',
  'f6_d': 'Sin red, sin telemetría, sin cuentas.',
  'how_h': 'Cómo usarlo',
  's1': 'Mantén <kbd>⌘</kbd> y arrastra los iconos que quieras ocultar para que queden a la <strong>izquierda</strong> del separador de CleanMenuBar.',
  's2': 'Todo lo que esté a la <strong>derecha</strong> del separador permanece siempre visible.',
  's3': 'Haz clic en la flecha para contraer o expandir, o pulsa <kbd>⌃⌥⌘C</kbd> desde cualquier sitio.',
  's4': 'Cuando lo tengas organizado, activa <strong>Ocultar los separadores</strong> para dejar solo la flecha.',
  'how_note': 'Las posiciones sobreviven a los reinicios: macOS recuerda dónde quedó cada icono.',
  'install_h': 'Instalación',
  'install_1': 'Descarga el <code>.dmg</code>, arrastra CleanMenuBar a Aplicaciones y ábrelo.',
  'install_note': 'La app está firmada con Developer ID y notarizada por Apple, así que se abre sin advertencias. Hasta que llegue a la Mac App Store, la descarga de arriba es la forma oficial de obtenerla.',
  'nav_home': 'Inicio',
  'nav_privacy': 'Privacidad',
  'nav_terms': 'Términos de uso',
  'licence_short': 'Licencia MIT',
  'pp_title': 'Política de Privacidad',
  'pp_meta': 'CleanMenuBar · Actualizado el {date} · Se aplica a todas las versiones',
  'pp_short_h': 'Resumen',
  'pp_short_1': 'CleanMenuBar no recopila nada, no envía nada y no tiene servidores.',
  'pp_short_note': 'Esto no es una decisión de política que pudiera cambiar en silencio: es lo que la app es técnicamente capaz de hacer. Se ejecuta dentro del App Sandbox de Apple <strong>sin permiso de red</strong>, de modo que no podría abrir una conexión aunque su código lo intentara.',
  'pp_store_h': 'Qué se almacena',
  'pp_store_1': 'Tus ajustes — el idioma, el atajo, si la contracción automática está activada y tras cuánto tiempo — se escriben en el almacén de preferencias estándar de macOS, dentro del contenedor aislado de la propia app:',
  'pp_store_2': 'Esto permanece en tu Mac. No se transmite, no lo copiamos y no podemos leerlo. Eliminar la app y esa carpeta borra todo lo que CleanMenuBar haya escrito.',
  'pp_store_3': 'Por separado, macOS recuerda dónde arrastraste los iconos. Ese es un registro del propio sistema, no nuestro, y vive fuera de la app.',
  'pp_not_h': 'Qué no hace la app',
  'pp_n1': 'Sin analíticas, telemetría, informes de fallos ni estadísticas de uso',
  'pp_n2': 'Sin cuentas, inicios de sesión ni identificadores',
  'pp_n3': 'Sin publicidad y sin compartir datos con nadie',
  'pp_n4': 'Sin peticiones de red de ningún tipo',
  'pp_n5': 'Sin acceso a tus archivos, contactos, cámara, micrófono ni ubicación',
  'pp_perm_h': 'Permisos',
  'pp_perm_1': 'CleanMenuBar no solicita <strong>ningún</strong> permiso especial. No necesita Accesibilidad ni Grabación de Pantalla, lo que lo distingue de la mayoría de herramientas de barra de menús: el atajo global usa una API que funciona sin ellos, y la app nunca lee la pantalla.',
  'pp_perm_2': 'Si macOS alguna vez te pide un permiso en nombre de CleanMenuBar, considéralo un error y avísanos.',
  'pp_kids_h': 'Menores',
  'pp_kids_1': 'CleanMenuBar no está dirigido a menores y no recopila datos de nadie, sea cual sea su edad.',
  'pp_src_h': 'El código es público',
  'pp_src_1': 'No hace falta que confíes en nada de esto. El código fuente completo está publicado bajo Licencia MIT, incluido el archivo de entitlements que declara qué puede hacer la app.',
  'pp_chg_h': 'Cambios',
  'pp_chg_1': 'Si esta política cambia, la versión revisada se publicará aquí con una nueva fecha. Como la app no recopila nada, cualquier cambio relevante exigiría una nueva versión, y la diferencia en el código lo mostraría.',
  'contact_h': 'Contacto',
  'tu_title': 'Términos de Uso',
  'tu_meta': 'CleanMenuBar · Actualizado el {date}',
  'tu_who_h': '1. Quién proporciona el software',
  'tu_who_1': 'CleanMenuBar es proporcionado por <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>, contacto <a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>.',
  'tu_lic_h': '2. Licencia',
  'tu_lic_1': 'CleanMenuBar es software libre distribuido bajo la <strong>Licencia MIT</strong>. Puedes usarlo, copiarlo, modificarlo, distribuirlo e incluso venderlo, gratuitamente, siempre que conserves el aviso de derechos de autor y el texto de la licencia en todas las copias.',
  'tu_lic_2': 'El texto completo acompaña a cada copia de la app, accesible en <strong>Acerca de → Licencias</strong>.',
  'tu_lic_3': 'CleanMenuBar deriva de <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a>, de Dwarves Foundation, también bajo Licencia MIT. Su aviso de copyright acompaña a la app.',
  'tu_war_h': '3. Ausencia de garantía',
  'tu_war_1': 'El software se proporciona <strong>“tal cual”</strong>, sin garantía de ningún tipo, expresa o implícita, incluidas, entre otras, las garantías de comerciabilidad, idoneidad para un fin determinado y no infracción.',
  'tu_war_2': 'No garantizamos que la app funcione sin interrupciones ni errores, ni que sea compatible con una configuración de hardware, versión de macOS o combinación de software concretas.',
  'tu_lia_h': '4. Limitación de responsabilidad',
  'tu_lia_1': 'En la máxima medida permitida por la legislación aplicable, los autores y titulares de los derechos no serán responsables de ninguna reclamación, daño u otra responsabilidad, ya sea contractual, extracontractual o de otra índole, derivada del software o de su uso.',
  'tu_lia_2': 'Esto incluye, sin limitación, pérdida de datos, lucro cesante, interrupción de la actividad y daños indirectos o incidentales.',
  'tu_lia_3': 'Nada en estos Términos excluye o limita responsabilidades que no puedan excluirse o limitarse conforme a la legislación brasileña aplicable, incluida la de protección al consumidor.',
  'tu_risk_h': '5. Uso bajo tu propia responsabilidad',
  'tu_risk_1': 'CleanMenuBar cambia cómo se muestran los iconos en la barra de menús de macOS usando solo API públicas de Apple. Aun así, el comportamiento de la barra puede cambiar entre versiones del sistema, y las actualizaciones de macOS pueden afectar al funcionamiento de la app.',
  'tu_risk_2': 'Eres responsable de mantener copias de seguridad de tus datos y de valorar si el software se ajusta a tu uso.',
  'tu_priv_h': '6. Privacidad',
  'tu_priv_1': 'CleanMenuBar no recopila, transmite ni almacena remotamente ningún dato.',
  'tu_chg_h': '7. Cambios',
  'tu_chg_1': 'Estos Términos pueden actualizarse. La versión vigente es siempre la publicada en esta página, con la fecha indicada arriba.',
  'tu_law_h': '8. Legislación aplicable',
  'tu_law_1': 'Estos Términos se rigen por la legislación brasileña.',
}

C['fr'] = {
  'title': 'CleanMenuBar — masquer les icônes de la barre des menus sur macOS 27',
  'description': 'CleanMenuBar masque les icônes de votre barre des menus macOS. Open source, gratuit, ne collecte rien.',
  'tagline': 'Masquez les icônes de la barre des menus que vous ne voulez pas voir.',
  'download': 'Télécharger pour macOS',
  'requirements': 'Gratuit et open source · macOS 26 ou ultérieur · Apple Silicon et Intel',
  'why_h': 'Pourquoi il existe',
  'why_1': "macOS 27 a reconstruit la barre des menus en une seule fenêtre et a cassé Hidden Bar, l'app que j'utilisais pour masquer des icônes. Elle reposait sur une technique qui a cessé de fonctionner.",
  'why_2': 'CleanMenuBar est une implémentation dérivée de Hidden Bar, au mécanisme adapté, créée et mesurée directement sur macOS 27 Golden Gate un jour après sa sortie publique (14/09/2026).',
  'what_h': "Ce qu'il fait",
  'f1_t': 'Masquer et afficher',
  'f1_d': 'Un clic, un raccourci global, ou simplement le survol.',
  'f2_t': 'Section toujours masquée',
  'f2_d': 'Une seconde zone qui reste masquée même dépliée.',
  'f3_t': 'Repli automatique',
  'f3_d': 'Après 5, 10, 15, 30 ou 60 secondes.',
  'f4_t': 'Aucune autorisation',
  'f4_d': "Ni Accessibilité ni Enregistrement de l'écran. Fonctionne en bac à sable.",
  'f5_t': 'Neuf langues',
  'f5_d': 'Français, anglais, portugais, espagnol, allemand, japonais, chinois et russe.',
  'f6_t': 'Ne collecte rien',
  'f6_d': 'Pas de réseau, pas de télémétrie, pas de comptes.',
  'how_h': 'Mise en route',
  's1': 'Maintenez <kbd>⌘</kbd> et faites glisser les icônes à masquer pour les placer à <strong>gauche</strong> du séparateur CleanMenuBar.',
  's2': 'Tout ce qui se trouve à <strong>droite</strong> du séparateur reste toujours visible.',
  's3': "Cliquez sur la flèche pour replier ou déplier, ou appuyez sur <kbd>⌃⌥⌘C</kbd> depuis n'importe où.",
  's4': 'Une fois tout en place, activez <strong>Masquer les séparateurs</strong> pour ne laisser que la flèche.',
  'how_note': 'Les positions survivent au redémarrage : macOS retient où chaque icône se trouve.',
  'install_h': 'Installation',
  'install_1': 'Téléchargez le <code>.dmg</code>, glissez CleanMenuBar dans Applications, puis ouvrez-le.',
  'install_note': "L'app est signée avec un Developer ID et notarisée par Apple : elle s'ouvre sans avertissement. En attendant le Mac App Store, le téléchargement ci-dessus est la voie officielle.",
  'nav_home': 'Accueil',
  'nav_privacy': 'Confidentialité',
  'nav_terms': "Conditions d'utilisation",
  'licence_short': 'Licence MIT',
  'pp_title': 'Politique de confidentialité',
  'pp_meta': "CleanMenuBar · Mis à jour le {date} · S'applique à toutes les versions",
  'pp_short_h': 'En bref',
  'pp_short_1': "CleanMenuBar ne collecte rien, n'envoie rien et n'a aucun serveur.",
  'pp_short_note': "Ce n'est pas un choix de politique qui pourrait changer discrètement : c'est ce dont l'app est techniquement capable. Elle s'exécute dans le bac à sable d'Apple <strong>sans autorisation réseau</strong>, elle ne pourrait donc ouvrir aucune connexion même si son code essayait.",
  'pp_store_h': 'Ce qui est stocké',
  'pp_store_1': "Vos réglages — la langue, le raccourci, l'état du repli automatique et son délai — sont écrits dans le stockage de préférences standard de macOS, à l'intérieur du conteneur isolé de l'app :",
  'pp_store_2': "Cela reste sur votre Mac. Rien n'est transmis, rien n'est sauvegardé par nous, rien n'est lisible par nous. Supprimer l'app et ce dossier efface tout ce que CleanMenuBar a écrit.",
  'pp_store_3': "Séparément, macOS retient où vous avez déplacé vos icônes. C'est un enregistrement du système, pas le nôtre, et il vit hors de l'app.",
  'pp_not_h': "Ce que l'app ne fait pas",
  'pp_n1': "Aucune analyse, télémétrie, rapport de plantage ni statistique d'usage",
  'pp_n2': 'Aucun compte, identifiant ni connexion',
  'pp_n3': 'Aucune publicité, aucune donnée partagée avec qui que ce soit',
  'pp_n4': "Aucune requête réseau, d'aucune sorte",
  'pp_n5': 'Aucun accès à vos fichiers, contacts, caméra, micro ou position',
  'pp_perm_h': 'Autorisations',
  'pp_perm_1': "CleanMenuBar ne demande <strong>aucune</strong> autorisation particulière. Ni Accessibilité ni Enregistrement de l'écran, ce qui le distingue de la plupart des outils de barre des menus : le raccourci global utilise une API qui s'en passe, et l'app ne lit jamais l'écran.",
  'pp_perm_2': 'Si macOS vous demande un jour une autorisation au nom de CleanMenuBar, considérez-le comme un bug et signalez-le.',
  'pp_kids_h': 'Enfants',
  'pp_kids_1': "CleanMenuBar ne s'adresse pas aux enfants et ne collecte les données de personne, quel que soit l'âge.",
  'pp_src_h': 'Le code est public',
  'pp_src_1': "Vous n'avez pas à nous croire sur parole. Le code source complet est publié sous licence MIT, y compris le fichier d'entitlements qui déclare ce que l'app a le droit de faire.",
  'pp_chg_h': 'Modifications',
  'pp_chg_1': "Si cette politique change, la version révisée sera publiée ici avec une nouvelle date. Comme l'app ne collecte rien, tout changement significatif exigerait une nouvelle version — et le diff du code le montrerait.",
  'contact_h': 'Contact',
  'tu_title': "Conditions d'utilisation",
  'tu_meta': 'CleanMenuBar · Mis à jour le {date}',
  'tu_who_h': '1. Qui fournit le logiciel',
  'tu_who_1': 'CleanMenuBar est fourni par <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>, contact <a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>.',
  'tu_lic_h': '2. Licence',
  'tu_lic_1': "CleanMenuBar est un logiciel libre distribué sous <strong>licence MIT</strong>. Vous pouvez l'utiliser, le copier, le modifier, le distribuer et même le vendre, gratuitement, à condition de conserver l'avis de droit d'auteur et le texte de la licence dans toutes les copies.",
  'tu_lic_2': "Le texte complet accompagne chaque copie de l'app, accessible via <strong>À propos → Licences</strong>.",
  'tu_lic_3': 'CleanMenuBar dérive de <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a> de Dwarves Foundation, également sous licence MIT. Leur avis de droit d\'auteur accompagne l\'app.',
  'tu_war_h': '3. Absence de garantie',
  'tu_war_1': "Le logiciel est fourni <strong>« en l'état »</strong>, sans garantie d'aucune sorte, expresse ou implicite, y compris, sans s'y limiter, les garanties de qualité marchande, d'adéquation à un usage particulier et d'absence de contrefaçon.",
  'tu_war_2': "Nous ne garantissons pas que l'app fonctionnera sans interruption ni erreur, ni qu'elle sera compatible avec une configuration matérielle, une version de macOS ou une combinaison de logiciels données.",
  'tu_lia_h': '4. Limitation de responsabilité',
  'tu_lia_1': 'Dans la mesure maximale permise par la loi applicable, les auteurs et titulaires des droits ne sauraient être tenus responsables de toute réclamation, dommage ou autre responsabilité, contractuelle, délictuelle ou autre, découlant du logiciel ou de son utilisation.',
  'tu_lia_2': "Cela inclut, sans limitation, la perte de données, le manque à gagner, l'interruption d'activité et les dommages indirects ou accessoires.",
  'tu_lia_3': "Rien dans ces Conditions n'exclut ni ne limite une responsabilité qui ne peut être exclue ou limitée en vertu du droit brésilien applicable, y compris le droit de la consommation.",
  'tu_risk_h': '5. Utilisation à vos risques',
  'tu_risk_1': "CleanMenuBar modifie l'affichage des icônes de la barre des menus en n'utilisant que des API publiques d'Apple. Le comportement de la barre peut néanmoins changer d'une version du système à l'autre, et les mises à jour de macOS peuvent affecter le fonctionnement de l'app.",
  'tu_risk_2': 'Il vous appartient de sauvegarder vos données et de juger si le logiciel convient à votre usage.',
  'tu_priv_h': '6. Confidentialité',
  'tu_priv_1': 'CleanMenuBar ne collecte, ne transmet et ne stocke à distance aucune donnée.',
  'tu_chg_h': '7. Modifications',
  'tu_chg_1': 'Ces Conditions peuvent être mises à jour. La version en vigueur est toujours celle publiée sur cette page, à la date indiquée ci-dessus.',
  'tu_law_h': '8. Droit applicable',
  'tu_law_1': 'Ces Conditions sont régies par le droit brésilien.',
}

C['de'] = {
  'title': 'CleanMenuBar — Menüleistensymbole unter macOS 27 ausblenden',
  'description': 'CleanMenuBar blendet Symbole in der macOS-Menüleiste aus. Open Source, kostenlos, sammelt nichts.',
  'tagline': 'Blenden Sie die Menüleistensymbole aus, die Sie nicht sehen möchten.',
  'download': 'Für macOS laden',
  'requirements': 'Kostenlos und Open Source · macOS 26 oder neuer · Apple Silicon und Intel',
  'why_h': 'Warum es das gibt',
  'why_1': 'macOS 27 hat die Menüleiste als einzelnes Fenster neu aufgebaut und dabei Hidden Bar zerstört — die App, mit der ich Symbole ausgeblendet habe. Sie stützte sich auf eine Technik, die nicht mehr funktioniert.',
  'why_2': 'CleanMenuBar ist eine von Hidden Bar abgeleitete Umsetzung mit angepasstem Mechanismus, entwickelt und vermessen direkt auf macOS 27 Golden Gate, einen Tag nach dessen Veröffentlichung (14.09.2026).',
  'what_h': 'Was es kann',
  'f1_t': 'Aus- und einblenden',
  'f1_d': 'Ein Klick, ein globaler Kurzbefehl oder einfach der Mauszeiger.',
  'f2_t': 'Immer ausgeblendeter Bereich',
  'f2_d': 'Ein zweiter Abschnitt, der auch beim Ausklappen verborgen bleibt.',
  'f3_t': 'Automatisches Einklappen',
  'f3_d': 'Nach 5, 10, 15, 30 oder 60 Sekunden.',
  'f4_t': 'Keine Berechtigungen',
  'f4_d': 'Keine Bedienungshilfen, keine Bildschirmaufnahme. Läuft in der Sandbox.',
  'f5_t': 'Neun Sprachen',
  'f5_d': 'Deutsch, Englisch, Portugiesisch, Spanisch, Französisch, Japanisch, Chinesisch und Russisch.',
  'f6_t': 'Sammelt nichts',
  'f6_d': 'Kein Netzwerk, keine Telemetrie, keine Konten.',
  'how_h': 'Einrichtung',
  's1': 'Halten Sie <kbd>⌘</kbd> gedrückt und ziehen Sie die auszublendenden Symbole <strong>links</strong> neben den CleanMenuBar-Trenner.',
  's2': 'Alles <strong>rechts</strong> vom Trenner bleibt dauerhaft sichtbar.',
  's3': 'Klicken Sie auf den Pfeil zum Ein- oder Ausklappen, oder drücken Sie überall <kbd>⌃⌥⌘C</kbd>.',
  's4': 'Wenn alles angeordnet ist, aktivieren Sie <strong>Trenner ausblenden</strong>, sodass nur der Pfeil bleibt.',
  'how_note': 'Die Positionen überstehen einen Neustart — macOS merkt sich, wo jedes Symbol sitzt.',
  'install_h': 'Installation',
  'install_1': 'Laden Sie das <code>.dmg</code>, ziehen Sie CleanMenuBar in „Programme“ und öffnen Sie es.',
  'install_note': 'Die App ist mit einer Developer ID signiert und von Apple notarisiert, öffnet also ohne Warnungen. Bis sie im Mac App Store ist, ist der Download oben der offizielle Weg.',
  'nav_home': 'Start',
  'nav_privacy': 'Datenschutz',
  'nav_terms': 'Nutzungsbedingungen',
  'licence_short': 'MIT-Lizenz',
  'pp_title': 'Datenschutzerklärung',
  'pp_meta': 'CleanMenuBar · Aktualisiert am {date} · Gilt für alle Versionen',
  'pp_short_h': 'Kurzfassung',
  'pp_short_1': 'CleanMenuBar sammelt nichts, sendet nichts und hat keine Server.',
  'pp_short_note': 'Das ist keine Richtlinienentscheidung, die sich still ändern könnte — es ist das, wozu die App technisch in der Lage ist. Sie läuft in Apples App-Sandbox <strong>ohne Netzwerkberechtigung</strong> und könnte daher keine Verbindung öffnen, selbst wenn ihr Code es versuchte.',
  'pp_store_h': 'Was gespeichert wird',
  'pp_store_1': 'Ihre Einstellungen — Sprache, Kurzbefehl, ob automatisches Einklappen aktiv ist und nach welcher Zeit — werden im Standard-Einstellungsspeicher von macOS abgelegt, im eigenen Sandbox-Container der App:',
  'pp_store_2': 'Das bleibt auf Ihrem Mac. Es wird nicht übertragen, von uns nicht gesichert und von uns nicht gelesen. Das Löschen der App und dieses Ordners entfernt alles, was CleanMenuBar je geschrieben hat.',
  'pp_store_3': 'Unabhängig davon merkt sich macOS, wohin Sie Ihre Menüleistensymbole gezogen haben. Das ist eine Aufzeichnung des Systems, nicht unsere, und sie liegt außerhalb der App.',
  'pp_not_h': 'Was die App nicht tut',
  'pp_n1': 'Keine Analysen, Telemetrie, Absturzberichte oder Nutzungsstatistiken',
  'pp_n2': 'Keine Konten, Anmeldungen oder Kennungen',
  'pp_n3': 'Keine Werbung, und keine Daten, die mit irgendjemandem geteilt werden',
  'pp_n4': 'Keinerlei Netzwerkanfragen',
  'pp_n5': 'Kein Zugriff auf Dateien, Kontakte, Kamera, Mikrofon oder Standort',
  'pp_perm_h': 'Berechtigungen',
  'pp_perm_1': 'CleanMenuBar fordert <strong>keine</strong> besonderen Berechtigungen an. Weder Bedienungshilfen noch Bildschirmaufnahme — anders als die meisten Menüleisten-Werkzeuge: Der globale Kurzbefehl nutzt eine API, die ohne sie auskommt, und die App liest den Bildschirm nie.',
  'pp_perm_2': 'Sollte macOS je eine Berechtigung im Namen von CleanMenuBar verlangen, betrachten Sie das als Fehler und melden Sie es.',
  'pp_kids_h': 'Kinder',
  'pp_kids_1': 'CleanMenuBar richtet sich nicht an Kinder und sammelt von niemandem Daten, unabhängig vom Alter.',
  'pp_src_h': 'Der Quellcode ist öffentlich',
  'pp_src_1': 'Sie müssen nichts davon glauben. Der vollständige Quellcode ist unter der MIT-Lizenz veröffentlicht, einschließlich der Entitlements-Datei, die festlegt, was die App darf.',
  'pp_chg_h': 'Änderungen',
  'pp_chg_1': 'Sollte sich diese Erklärung ändern, wird die überarbeitete Fassung hier mit neuem Datum veröffentlicht. Da die App nichts sammelt, würde jede bedeutsame Änderung eine neue Version erfordern — und der Quellcode-Diff würde sie zeigen.',
  'contact_h': 'Kontakt',
  'tu_title': 'Nutzungsbedingungen',
  'tu_meta': 'CleanMenuBar · Aktualisiert am {date}',
  'tu_who_h': '1. Wer die Software bereitstellt',
  'tu_who_1': 'CleanMenuBar wird bereitgestellt von <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>, Kontakt <a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>.',
  'tu_lic_h': '2. Lizenz',
  'tu_lic_1': 'CleanMenuBar ist freie Software unter der <strong>MIT-Lizenz</strong>. Sie dürfen sie kostenlos nutzen, kopieren, verändern, verbreiten und sogar verkaufen, sofern Sie den Urheberrechtshinweis und den Lizenztext in allen Kopien beibehalten.',
  'tu_lic_2': 'Der vollständige Text liegt jeder Kopie der App bei, erreichbar über <strong>Über → Lizenzen</strong>.',
  'tu_lic_3': 'CleanMenuBar leitet sich von <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a> der Dwarves Foundation ab, ebenfalls unter MIT-Lizenz. Deren Urheberrechtshinweis liegt der App bei.',
  'tu_war_h': '3. Keine Gewährleistung',
  'tu_war_1': 'Die Software wird <strong>„wie besehen“</strong> bereitgestellt, ohne Gewährleistung jeder Art, ausdrücklich oder stillschweigend, einschließlich, aber nicht beschränkt auf die Gewährleistung der Marktgängigkeit, der Eignung für einen bestimmten Zweck und der Nichtverletzung von Rechten.',
  'tu_war_2': 'Wir gewährleisten nicht, dass die App unterbrechungs- oder fehlerfrei läuft oder mit einer bestimmten Hardwarekonfiguration, macOS-Version oder Softwarekombination kompatibel ist.',
  'tu_lia_h': '4. Haftungsbeschränkung',
  'tu_lia_1': 'Soweit nach geltendem Recht zulässig, haften die Autoren und Rechteinhaber nicht für Ansprüche, Schäden oder sonstige Haftung, sei es aus Vertrag, unerlaubter Handlung oder anderweitig, die sich aus der Software oder ihrer Nutzung ergeben.',
  'tu_lia_2': 'Dies umfasst ohne Einschränkung Datenverlust, entgangenen Gewinn, Betriebsunterbrechung sowie mittelbare oder beiläufige Schäden.',
  'tu_lia_3': 'Nichts in diesen Bedingungen schließt eine Haftung aus oder begrenzt sie, die nach geltendem brasilianischem Recht, einschließlich des Verbraucherschutzrechts, nicht ausgeschlossen oder begrenzt werden kann.',
  'tu_risk_h': '5. Nutzung auf eigenes Risiko',
  'tu_risk_1': 'CleanMenuBar verändert die Darstellung von Symbolen in der macOS-Menüleiste ausschließlich über öffentliche Apple-APIs. Dennoch kann sich das Verhalten der Menüleiste zwischen Systemversionen ändern, und macOS-Updates können die Funktion der App beeinträchtigen.',
  'tu_risk_2': 'Sie sind dafür verantwortlich, Ihre Daten zu sichern und zu beurteilen, ob die Software für Ihren Einsatz geeignet ist.',
  'tu_priv_h': '6. Datenschutz',
  'tu_priv_1': 'CleanMenuBar sammelt, überträgt und speichert nichts aus der Ferne.',
  'tu_chg_h': '7. Änderungen',
  'tu_chg_1': 'Diese Bedingungen können aktualisiert werden. Es gilt stets die auf dieser Seite veröffentlichte Fassung mit dem oben genannten Datum.',
  'tu_law_h': '8. Anwendbares Recht',
  'tu_law_1': 'Diese Bedingungen unterliegen brasilianischem Recht.',
}

C['ja'] = {
  'title': 'CleanMenuBar — macOS 27でメニューバーのアイコンを隠す',
  'description': 'CleanMenuBarはmacOSのメニューバーアイコンを隠します。オープンソース、無料、何も収集しません。',
  'tagline': '見たくないメニューバーのアイコンを隠します。',
  'download': 'macOS版をダウンロード',
  'requirements': '無料・オープンソース · macOS 26以降 · Apple SiliconとIntel',
  'why_h': '開発の理由',
  'why_1': 'macOS 27はメニューバーを単一のウインドウとして作り直し、私が使っていたアイコン非表示アプリ「Hidden Bar」を壊しました。同アプリが頼っていた手法が、動かなくなったのです。',
  'why_2': 'CleanMenuBarはHidden Barから派生し、仕組みを作り替えた実装です。macOS 27 Golden Gateの一般公開の翌日（2026年9月14日公開）に、その環境上で直接開発・実測しました。',
  'what_h': 'できること',
  'f1_t': '隠す・表示する',
  'f1_d': 'クリック、グローバルショートカット、またはポインタを重ねるだけ。',
  'f2_t': '常に非表示のセクション',
  'f2_d': '展開してもなお隠れたままの第二の領域。',
  'f3_t': '自動折りたたみ',
  'f3_d': '5、10、15、30、60秒後に。',
  'f4_t': '権限は不要',
  'f4_d': 'アクセシビリティも画面収録も不要。サンドボックス内で動作します。',
  'f5_t': '9言語対応',
  'f5_d': '日本語、英語、ポルトガル語、スペイン語、フランス語、ドイツ語、中国語、ロシア語。',
  'f6_t': '何も収集しません',
  'f6_d': 'ネットワークなし、テレメトリなし、アカウントなし。',
  'how_h': '使い方',
  's1': '<kbd>⌘</kbd>を押しながら、隠したいアイコンをCleanMenuBarの区切りの<strong>左側</strong>へドラッグします。',
  's2': '区切りの<strong>右側</strong>にあるものは常に表示されたままです。',
  's3': '矢印をクリックして折りたたみ・展開するか、どこからでも<kbd>⌃⌥⌘C</kbd>を押します。',
  's4': '並べ替えが終わったら<strong>区切りを隠す</strong>をオンにして、矢印だけを残します。',
  'how_note': '位置は再起動後も保たれます。macOSが各アイコンの場所を記憶します。',
  'install_h': 'インストール',
  'install_1': '<code>.dmg</code>をダウンロードし、CleanMenuBarをアプリケーションフォルダにドラッグして開きます。',
  'install_note': '本アプリはDeveloper IDで署名され、Appleの公証を受けているため、警告なしに開きます。Mac App Storeに並ぶまでは、上記のダウンロードが公式の入手方法です。',
  'nav_home': 'ホーム',
  'nav_privacy': 'プライバシー',
  'nav_terms': '利用規約',
  'licence_short': 'MITライセンス',
  'pp_title': 'プライバシーポリシー',
  'pp_meta': 'CleanMenuBar · {date}更新 · すべてのバージョンに適用',
  'pp_short_h': '要約',
  'pp_short_1': 'CleanMenuBarは何も収集せず、何も送信せず、サーバーを持ちません。',
  'pp_short_note': 'これは静かに変更されうる方針ではなく、アプリが技術的にできることそのものです。AppleのApp Sandbox内で<strong>ネットワーク権限なし</strong>で動作するため、コードが試みても接続を開けません。',
  'pp_store_h': '保存されるもの',
  'pp_store_1': '設定——言語、ショートカット、自動折りたたみの有無とその秒数——は、macOS標準の設定保存領域、つまりアプリ専用のサンドボックスコンテナ内に書き込まれます。',
  'pp_store_2': 'これはあなたのMacに留まります。送信されず、こちらでバックアップされず、こちらから読めません。アプリとそのフォルダを削除すれば、CleanMenuBarが書いたものはすべて消えます。',
  'pp_store_3': 'これとは別に、macOSがメニューバーアイコンの配置を記憶します。これはシステム自身の記録であり、当方のものではなく、アプリの外にあります。',
  'pp_not_h': 'アプリが行わないこと',
  'pp_n1': '分析、テレメトリ、クラッシュレポート、利用統計を一切行いません',
  'pp_n2': 'アカウント、ログイン、識別子を持ちません',
  'pp_n3': '広告はなく、いかなる相手ともデータを共有しません',
  'pp_n4': 'いかなる種類のネットワーク通信も行いません',
  'pp_n5': 'ファイル、連絡先、カメラ、マイク、位置情報にアクセスしません',
  'pp_perm_h': '権限',
  'pp_perm_1': 'CleanMenuBarは特別な権限を<strong>一切</strong>要求しません。アクセシビリティも画面収録も不要で、この点が多くのメニューバーツールと異なります。グローバルショートカットはそれらを必要としないAPIを使い、アプリが画面を読むことはありません。',
  'pp_perm_2': 'もしmacOSがCleanMenuBarのために権限を求めてきた場合は、不具合としてご報告ください。',
  'pp_kids_h': '子どもについて',
  'pp_kids_1': 'CleanMenuBarは子ども向けではなく、年齢を問わず誰からもデータを収集しません。',
  'pp_src_h': 'ソースは公開されています',
  'pp_src_1': 'これらを鵜呑みにする必要はありません。完全なソースコードはMITライセンスで公開されており、アプリに許可された動作を宣言するentitlementsファイルも含まれます。',
  'pp_chg_h': '変更',
  'pp_chg_1': '本ポリシーが変更される場合、改訂版が新しい日付とともにこのページに掲載されます。アプリは何も収集しないため、意味のある変更には新しいリリースが必要であり、ソースの差分に現れます。',
  'contact_h': '連絡先',
  'tu_title': '利用規約',
  'tu_meta': 'CleanMenuBar · {date}更新',
  'tu_who_h': '1. ソフトウェアの提供者',
  'tu_who_1': 'CleanMenuBarは<strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>が提供します。連絡先：<a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>',
  'tu_lic_h': '2. ライセンス',
  'tu_lic_1': 'CleanMenuBarは<strong>MITライセンス</strong>で配布される自由ソフトウェアです。著作権表示とライセンス本文をすべての複製に保持する限り、無償で使用、複製、改変、配布、さらには販売もできます。',
  'tu_lic_2': '全文はアプリの各コピーに同梱され、<strong>情報 → ライセンス</strong>から参照できます。',
  'tu_lic_3': 'CleanMenuBarはDwarves Foundationの<a href="https://github.com/dwarvesf/hidden">Hidden Bar</a>（同じくMITライセンス）に由来します。同団体の著作権表示もアプリに同梱されています。',
  'tu_war_h': '3. 無保証',
  'tu_war_1': '本ソフトウェアは<strong>「現状のまま」</strong>提供され、明示黙示を問わず、商品性、特定目的への適合性、権利非侵害を含むいかなる保証も伴いません。',
  'tu_war_2': '中断なく、または誤りなく動作すること、特定のハードウェア構成・macOSバージョン・他のソフトウェアとの組み合わせで動作することを保証しません。',
  'tu_lia_h': '4. 責任の制限',
  'tu_lia_1': '適用法が認める最大限の範囲において、著作者および著作権者は、契約、不法行為その他を問わず、本ソフトウェアまたはその使用に起因するいかなる請求、損害、責任についても責任を負いません。',
  'tu_lia_2': 'これにはデータの喪失、逸失利益、業務の中断、間接的または付随的損害が含まれますが、これらに限りません。',
  'tu_lia_3': '本規約のいかなる規定も、消費者保護法を含む適用されるブラジル法の下で排除または制限できない責任を、排除または制限するものではありません。',
  'tu_risk_h': '5. 自己責任でのご利用',
  'tu_risk_1': 'CleanMenuBarはAppleの公開APIのみを用いてメニューバーのアイコン表示を変更します。それでもメニューバーの挙動はOSのバージョン間で変わりうるため、macOSの更新がアプリの動作に影響する場合があります。',
  'tu_risk_2': 'データのバックアップ、および本ソフトウェアがご自身の用途に適するかの判断は、利用者の責任となります。',
  'tu_priv_h': '6. プライバシー',
  'tu_priv_1': 'CleanMenuBarはいかなるデータも収集・送信・遠隔保存しません。',
  'tu_chg_h': '7. 変更',
  'tu_chg_1': '本規約は更新されることがあります。有効なのは常に本ページに掲載され、上記の日付を有する版です。',
  'tu_law_h': '8. 準拠法',
  'tu_law_1': '本規約はブラジル法に準拠します。',
}

C['zh-Hans'] = {
  'title': 'CleanMenuBar — 在 macOS 27 上隐藏菜单栏图标',
  'description': 'CleanMenuBar 隐藏 macOS 菜单栏图标。开源、免费、不收集任何数据。',
  'tagline': '隐藏你不想看到的菜单栏图标。',
  'download': '下载 macOS 版',
  'requirements': '免费开源 · macOS 26 或更高 · Apple Silicon 与 Intel',
  'why_h': '为什么会有它',
  'why_1': 'macOS 27 将菜单栏重建为单一窗口，并让我一直使用的隐藏图标 App「Hidden Bar」失效。它所依赖的技术不再奏效。',
  'why_2': 'CleanMenuBar 衍生自 Hidden Bar，机制经过改写，并在 macOS 27 Golden Gate 公开发布（2026 年 9 月 14 日）次日于该系统上直接开发与实测。',
  'what_h': '功能',
  'f1_t': '隐藏与显示',
  'f1_d': '点按、全局快捷键，或仅将指针悬停其上。',
  'f2_t': '始终隐藏区域',
  'f2_d': '即使展开也保持隐藏的第二段区域。',
  'f3_t': '自动折叠',
  'f3_d': '5、10、15、30 或 60 秒后。',
  'f4_t': '无需权限',
  'f4_d': '无需辅助功能，无需屏幕录制。运行于沙盒中。',
  'f5_t': '九种语言',
  'f5_d': '简体中文、繁体中文、英语、葡萄牙语、西班牙语、法语、德语、日语、俄语。',
  'f6_t': '不收集任何数据',
  'f6_d': '无网络、无遥测、无账户。',
  'how_h': '设置步骤',
  's1': '按住 <kbd>⌘</kbd>，将想隐藏的图标拖到 CleanMenuBar 分隔符的<strong>左侧</strong>。',
  's2': '位于分隔符<strong>右侧</strong>的图标始终保持可见。',
  's3': '点按箭头折叠或展开，或在任意位置按 <kbd>⌃⌥⌘C</kbd>。',
  's4': '整理完成后，开启<strong>隐藏分隔符</strong>，屏幕上便只留下箭头。',
  'how_note': '位置在重新启动后依然保留——macOS 会记住每个图标的位置。',
  'install_h': '安装',
  'install_1': '下载 <code>.dmg</code>，将 CleanMenuBar 拖入「应用程序」，然后打开。',
  'install_note': '该 App 使用 Developer ID 签名并经 Apple 公证，因此打开时不会出现警告。在上架 Mac App Store 之前，上方下载是官方获取方式。',
  'nav_home': '首页',
  'nav_privacy': '隐私',
  'nav_terms': '使用条款',
  'licence_short': 'MIT 许可证',
  'pp_title': '隐私政策',
  'pp_meta': 'CleanMenuBar · 更新于 {date} · 适用于所有版本',
  'pp_short_h': '简要说明',
  'pp_short_1': 'CleanMenuBar 不收集任何数据，不发送任何内容，也没有服务器。',
  'pp_short_note': '这并非可能悄然改变的政策选择，而是该 App 在技术上的能力边界。它在 Apple 的 App Sandbox 中运行且<strong>没有网络权限</strong>，即使代码尝试也无法建立连接。',
  'pp_store_h': '存储了什么',
  'pp_store_1': '你的设置——语言、快捷键、是否启用自动折叠及其延迟——被写入 macOS 的标准偏好设置存储，位于该 App 自己的沙盒容器内：',
  'pp_store_2': '这些内容留在你的 Mac 上。不会被传输，我们不会备份，也无法读取。删除 App 及该文件夹即可清除 CleanMenuBar 写入的一切。',
  'pp_store_3': '此外，macOS 会单独记住你拖动菜单栏图标的位置。那是系统自身的记录，不属于我们，且存在于 App 之外。',
  'pp_not_h': '该 App 不做什么',
  'pp_n1': '无分析、遥测、崩溃报告或使用统计',
  'pp_n2': '无账户、登录或标识符',
  'pp_n3': '无广告，也不与任何人共享数据',
  'pp_n4': '不发起任何形式的网络请求',
  'pp_n5': '不访问你的文件、通讯录、摄像头、麦克风或位置',
  'pp_perm_h': '权限',
  'pp_perm_1': 'CleanMenuBar <strong>不</strong>请求任何特殊权限。它既不需要辅助功能，也不需要屏幕录制——这一点有别于多数菜单栏工具：全局快捷键使用无需这些权限的 API，且该 App 从不读取屏幕。',
  'pp_perm_2': '若 macOS 曾以 CleanMenuBar 的名义请求权限，请视为缺陷并告知我们。',
  'pp_kids_h': '儿童',
  'pp_kids_1': 'CleanMenuBar 并非面向儿童，且不收集任何人的数据，无论年龄。',
  'pp_src_h': '源代码公开',
  'pp_src_1': '你无需仅凭信任接受以上说明。完整源代码以 MIT 许可证公开，其中包括声明 App 权限范围的 entitlements 文件。',
  'pp_chg_h': '变更',
  'pp_chg_1': '若本政策有所变更，修订版本将连同新日期发布于本页。由于该 App 不收集任何数据，任何实质性变更都需要新版本发布，而源代码差异会如实呈现。',
  'contact_h': '联系方式',
  'tu_title': '使用条款',
  'tu_meta': 'CleanMenuBar · 更新于 {date}',
  'tu_who_h': '1. 软件提供方',
  'tu_who_1': 'CleanMenuBar 由 <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong> 提供，联系方式：<a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>。',
  'tu_lic_h': '2. 许可',
  'tu_lic_1': 'CleanMenuBar 是依 <strong>MIT 许可证</strong>发布的自由软件。只要在所有副本中保留版权声明与许可证文本，你即可免费使用、复制、修改、分发，乃至出售。',
  'tu_lic_2': '完整文本随 App 的每一份副本一同提供，可在<strong>关于 → 许可证</strong>中查看。',
  'tu_lic_3': 'CleanMenuBar 源自 Dwarves Foundation 的 <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a>，同样采用 MIT 许可证。其版权声明亦随 App 提供。',
  'tu_war_h': '3. 不提供保证',
  'tu_war_1': '本软件按<strong>「现状」</strong>提供，不附带任何明示或默示的保证，包括但不限于适销性、特定用途适用性及不侵权的保证。',
  'tu_war_2': '我们不保证该 App 运行不中断或无错误，也不保证其与任何特定硬件配置、macOS 版本或其他软件组合兼容。',
  'tu_lia_h': '4. 责任限制',
  'tu_lia_1': '在适用法律允许的最大范围内，作者与版权持有人不对因本软件或其使用而产生的任何索赔、损害或其他责任负责，无论基于合同、侵权或其他。',
  'tu_lia_2': '这包括但不限于数据丢失、利润损失、业务中断以及间接或附带损害。',
  'tu_lia_3': '本条款中的任何内容，均不排除或限制依据适用的巴西法律（含消费者保护法）不得排除或限制的责任。',
  'tu_risk_h': '5. 使用风险自负',
  'tu_risk_1': 'CleanMenuBar 仅使用 Apple 的公开 API 改变菜单栏图标的显示方式。即便如此，菜单栏的行为可能随系统版本变化，macOS 更新也可能影响该 App 的运行。',
  'tu_risk_2': '你有责任备份自己的数据，并自行判断本软件是否适合你的用途。',
  'tu_priv_h': '6. 隐私',
  'tu_priv_1': 'CleanMenuBar 不收集、不传输、不远程存储任何数据。',
  'tu_chg_h': '7. 变更',
  'tu_chg_1': '本条款可能更新。现行版本始终是本页所发布、标注上述日期的版本。',
  'tu_law_h': '8. 适用法律',
  'tu_law_1': '本条款受巴西法律管辖。',
}

C['zh-Hant'] = {
  'title': 'CleanMenuBar — 在 macOS 27 上隱藏選單列圖像',
  'description': 'CleanMenuBar 隱藏 macOS 選單列圖像。開源、免費、不收集任何資料。',
  'tagline': '隱藏你不想看到的選單列圖像。',
  'download': '下載 macOS 版',
  'requirements': '免費開源 · macOS 26 或更高 · Apple Silicon 与 Intel',
  'why_h': '为什么会有它',
  'why_1': 'macOS 27 將選單列重建為單一視窗，並讓我一直使用的隱藏圖像 App「Hidden Bar」失效。它所依賴的技術不再奏效。',
  'why_2': 'CleanMenuBar 衍生自 Hidden Bar，機制經過改寫，並在 macOS 27 Golden Gate 公開發布（2026 年 9 月 14 日）次日於該系統上直接開發與實測。',
  'what_h': '功能',
  'f1_t': '隱藏与顯示',
  'f1_d': '點一下、全局快速鍵，或仅将指针停留其上。',
  'f2_t': '始終隱藏區域',
  'f2_d': '即使展開也保持隱藏的第二段區域。',
  'f3_t': '自动收合',
  'f3_d': '5、10、15、30 或 60 秒後。',
  'f4_t': '无需權限',
  'f4_d': '无需輔助使用，无需螢幕錄製。執行于沙箱中。',
  'f5_t': '九种語言',
  'f5_d': '繁體中文、簡體中文、英文、葡萄牙文、西班牙文、法文、德文、日文、俄文。',
  'f6_t': '不收集任何資料',
  'f6_d': '无網路、无遙測、无帳號。',
  'how_h': '設定步骤',
  's1': '按住 <kbd>⌘</kbd>，将想隱藏的圖像拖曳至 CleanMenuBar 分隔符號的<strong>左側</strong>。',
  's2': '位于分隔符號<strong>右側</strong>的圖像始終保持可見。',
  's3': '點一下箭頭收合或展開，或在任意位置按 <kbd>⌃⌥⌘C</kbd>。',
  's4': '整理完成後，開啟<strong>隱藏分隔符號</strong>，螢幕上便只留下箭頭。',
  'how_note': '位置在重新啟動后依然保留——macOS 会記住每个圖像的位置。',
  'install_h': '安裝',
  'install_1': '下載 <code>.dmg</code>，将 CleanMenuBar 拖入「應用程式」，然后開啟。',
  'install_note': '该 App 使用 Developer ID 簽署并经 Apple 公證，因此開啟时不会出现警告。在上架 Mac App Store 之前，上方下載是官方取得方式。',
  'nav_home': '首頁',
  'nav_privacy': '隱私',
  'nav_terms': '使用條款',
  'licence_short': 'MIT 授權條款',
  'pp_title': '隱私政策',
  'pp_meta': 'CleanMenuBar · 更新于 {date} · 適用於所有版本',
  'pp_short_h': '簡要說明',
  'pp_short_1': 'CleanMenuBar 不收集任何資料，不发送任何內容，也没有服务器。',
  'pp_short_note': '这並非可能悄然改變的政策選擇，而是该 App 在技术上的能力邊界。它在 Apple 的 App Sandbox 中執行且<strong>没有網路權限</strong>，即使程式碼嘗試也无法建立連線。',
  'pp_store_h': '儲存了什么',
  'pp_store_1': '你的設定——語言、快速鍵、是否启用自动收合及其延迟——被寫入 macOS 的标准偏好設定儲存，位于该 App 自己的沙箱容器内：',
  'pp_store_2': '这些內容留在你的 Mac 上。不会被傳輸，我们不会備份，也无法讀取。刪除 App 及该檔案夾即可清除 CleanMenuBar 寫入的一切。',
  'pp_store_3': '此外，macOS 会單獨記住你拖曳選單列圖像的位置。那是系統自身的記錄，不屬於我们，且存在于 App 之外。',
  'pp_not_h': '该 App 不做什麼',
  'pp_n1': '无分析、遙測、當機報告或使用統計',
  'pp_n2': '无帳號、登入或識別碼',
  'pp_n3': '无廣告，也不与任何人共享資料',
  'pp_n4': '不发起任何形式的網路請求',
  'pp_n5': '不存取你的檔案、通訊錄、攝影機、麥克風或位置',
  'pp_perm_h': '權限',
  'pp_perm_1': 'CleanMenuBar <strong>不</strong>請求任何特殊權限。它既不需要輔助使用，也不需要螢幕錄製——这一点有别于多数選單列工具：全局快速鍵使用无需这些權限的 API，且该 App 从不讀取螢幕。',
  'pp_perm_2': '若 macOS 曾以 CleanMenuBar 的名义請求權限，请视为瑕疵并告知我们。',
  'pp_kids_h': '兒童',
  'pp_kids_1': 'CleanMenuBar 並非面向兒童，且不收集任何人的資料，無論年齡。',
  'pp_src_h': '原始碼公開',
  'pp_src_1': '你无需僅憑信任接受以上說明。完整原始碼以 MIT 授權條款公開，其中包括聲明 App 權限範圍的 entitlements 檔案。',
  'pp_chg_h': '變更',
  'pp_chg_1': '若本政策有所變更，修訂版本将連同新日期發布于本页。由於该 App 不收集任何資料，任何實質變更都需要新版本發布，而原始碼差異会如實呈現。',
  'contact_h': '聯絡方式',
  'tu_title': '使用條款',
  'tu_meta': 'CleanMenuBar · 更新于 {date}',
  'tu_who_h': '1. 軟體提供者',
  'tu_who_1': 'CleanMenuBar 由 <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong> 提供，聯絡方式：<a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>。',
  'tu_lic_h': '2. 授權',
  'tu_lic_1': 'CleanMenuBar 是依 <strong>MIT 授權條款</strong>發布的自由軟體。只要在所有副本中保留版权聲明与授權條款文本，你即可免費使用、複製、修改、散布，乃至販售。',
  'tu_lic_2': '完整文本隨 App 的每一份副本一同提供，可在<strong>關於 → 授權條款</strong>中檢視。',
  'tu_lic_3': 'CleanMenuBar 源自 Dwarves Foundation 的 <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a>，同样採用 MIT 授權條款。其版权聲明亦隨 App 提供。',
  'tu_war_h': '3. 不提供保證',
  'tu_war_1': '本軟體按<strong>「現狀」</strong>提供，不附帶任何明示或默示的保證，包括但不限於適售性、特定用途適用性及不侵權的保證。',
  'tu_war_2': '我们不保證该 App 執行不中斷或无錯誤，也不保證其与任何特定硬體設定、macOS 版本或其他軟體組合相容。',
  'tu_lia_h': '4. 責任限制',
  'tu_lia_1': '在适用法律允許的最大範圍内，作者与版权持有人不对因本軟體或其使用而產生的任何索賠、損害或其他責任负责，無論基於合約、侵權或其他。',
  'tu_lia_2': '這包括但不限於資料遺失、利潤損失、營運中斷以及間接或附帶損害。',
  'tu_lia_3': '本條款中的任何內容，均不排除或限制依據适用的巴西法律（含消費者保護法）不得排除或限制的責任。',
  'tu_risk_h': '5. 使用風險自負',
  'tu_risk_1': 'CleanMenuBar 僅使用 Apple 的公開 API 改變選單列圖像的顯示方式。即便如此，選單列的行为可能隨系统版本變化，macOS 更新也可能影響该 App 的執行。',
  'tu_risk_2': '你有責任備份自己的資料，并自行判斷本軟體是否適合你的用途。',
  'tu_priv_h': '6. 隱私',
  'tu_priv_1': 'CleanMenuBar 不收集、不傳輸、不遠端儲存任何資料。',
  'tu_chg_h': '7. 變更',
  'tu_chg_1': '本條款可能更新。現行版本始終是本页所發布、標註上述日期的版本。',
  'tu_law_h': '8. 适用法律',
  'tu_law_1': '本條款受巴西法律管轄。',
}

C['ru'] = {
  'title': 'CleanMenuBar — скрыть значки строки меню в macOS 27',
  'description': 'CleanMenuBar скрывает значки строки меню macOS. Открытый исходный код, бесплатно, ничего не собирает.',
  'tagline': 'Скройте значки строки меню, которые не хотите видеть.',
  'download': 'Загрузить для macOS',
  'requirements': 'Бесплатно и с открытым кодом · macOS 26 или новее · Apple Silicon и Intel',
  'why_h': 'Зачем это нужно',
  'why_1': 'macOS 27 перестроил строку меню в одно окно и сломал Hidden Bar — программу, которой я пользовался, чтобы скрывать значки. Она опиралась на приём, переставший работать.',
  'why_2': 'CleanMenuBar — реализация, производная от Hidden Bar, с переработанным механизмом. Он создан и измерен непосредственно в macOS 27 Golden Gate на следующий день после публичного выпуска (14.09.2026).',
  'what_h': 'Что он умеет',
  'f1_t': 'Скрывать и показывать',
  'f1_d': 'Щелчок, глобальное сочетание клавиш или просто наведение курсора.',
  'f2_t': 'Всегда скрытая секция',
  'f2_d': 'Вторая область, которая остаётся скрытой даже при разворачивании.',
  'f3_t': 'Автосворачивание',
  'f3_d': 'Через 5, 10, 15, 30 или 60 секунд.',
  'f4_t': 'Никаких разрешений',
  'f4_d': 'Без «Универсального доступа» и записи экрана. Работает в песочнице.',
  'f5_t': 'Девять языков',
  'f5_d': 'Русский, английский, португальский, испанский, французский, немецкий, японский и китайский.',
  'f6_t': 'Ничего не собирает',
  'f6_d': 'Без сети, без телеметрии, без учётных записей.',
  'how_h': 'Настройка',
  's1': 'Удерживая <kbd>⌘</kbd>, перетащите значки, которые нужно скрыть, <strong>левее</strong> разделителя CleanMenuBar.',
  's2': 'Всё, что находится <strong>справа</strong> от разделителя, остаётся видимым всегда.',
  's3': 'Нажмите на стрелку, чтобы свернуть или развернуть, либо нажмите <kbd>⌃⌥⌘C</kbd> из любого места.',
  's4': 'Когда всё расставлено, включите <strong>Скрыть разделители</strong>, чтобы осталась только стрелка.',
  'how_note': 'Расположение сохраняется после перезапуска — macOS помнит, где стоит каждый значок.',
  'install_h': 'Установка',
  'install_1': 'Загрузите <code>.dmg</code>, перетащите CleanMenuBar в «Программы» и откройте.',
  'install_note': 'Программа подписана Developer ID и заверена Apple, поэтому открывается без предупреждений. Пока её нет в Mac App Store, загрузка выше — официальный способ получить её.',
  'nav_home': 'Главная',
  'nav_privacy': 'Конфиденциальность',
  'nav_terms': 'Условия использования',
  'licence_short': 'Лицензия MIT',
  'pp_title': 'Политика конфиденциальности',
  'pp_meta': 'CleanMenuBar · Обновлено {date} · Относится ко всем версиям',
  'pp_short_h': 'Коротко',
  'pp_short_1': 'CleanMenuBar ничего не собирает, ничего не отправляет и не имеет серверов.',
  'pp_short_note': 'Это не решение политики, которое могло бы незаметно измениться, — это то, на что программа технически способна. Она работает в песочнице Apple <strong>без сетевого разрешения</strong>, поэтому не смогла бы открыть соединение, даже если бы её код попытался.',
  'pp_store_h': 'Что сохраняется',
  'pp_store_1': 'Ваши настройки — язык, сочетание клавиш, включено ли автосворачивание и через сколько — записываются в стандартное хранилище настроек macOS, внутрь собственного контейнера программы:',
  'pp_store_2': 'Это остаётся на вашем Mac. Не передаётся, не резервируется нами и не может быть нами прочитано. Удаление программы и этой папки убирает всё, что CleanMenuBar когда-либо записал.',
  'pp_store_3': 'Отдельно macOS запоминает, куда вы перетащили значки строки меню. Это запись самой системы, не наша, и она находится вне программы.',
  'pp_not_h': 'Чего программа не делает',
  'pp_n1': 'Никакой аналитики, телеметрии, отчётов о сбоях и статистики использования',
  'pp_n2': 'Никаких учётных записей, входов и идентификаторов',
  'pp_n3': 'Никакой рекламы и никакой передачи данных кому бы то ни было',
  'pp_n4': 'Никаких сетевых запросов любого рода',
  'pp_n5': 'Никакого доступа к вашим файлам, контактам, камере, микрофону или геопозиции',
  'pp_perm_h': 'Разрешения',
  'pp_perm_1': 'CleanMenuBar не запрашивает <strong>никаких</strong> особых разрешений. Ему не нужны ни «Универсальный доступ», ни запись экрана — этим он отличается от большинства утилит для строки меню: глобальное сочетание использует API, работающий без них, и программа никогда не читает экран.',
  'pp_perm_2': 'Если macOS когда-либо запросит разрешение от имени CleanMenuBar, считайте это ошибкой и сообщите нам.',
  'pp_kids_h': 'Дети',
  'pp_kids_1': 'CleanMenuBar не предназначен для детей и не собирает данные ни у кого, независимо от возраста.',
  'pp_src_h': 'Исходный код открыт',
  'pp_src_1': 'Вам не нужно верить нам на слово. Полный исходный код опубликован под лицензией MIT, включая файл entitlements, который объявляет, что программе разрешено делать.',
  'pp_chg_h': 'Изменения',
  'pp_chg_1': 'Если эта политика изменится, новая редакция будет опубликована здесь с новой датой. Поскольку программа ничего не собирает, любое значимое изменение потребовало бы нового выпуска — и различия в исходном коде это показали бы.',
  'contact_h': 'Контакты',
  'tu_title': 'Условия использования',
  'tu_meta': 'CleanMenuBar · Обновлено {date}',
  'tu_who_h': '1. Кто предоставляет программу',
  'tu_who_1': 'CleanMenuBar предоставляется <strong>MONOBIT (ATILA VITAL CAVALCANTE DA SILVA LTDA)</strong>, контакт: <a href="mailto:apps@monobit.com.br">apps@monobit.com.br</a>.',
  'tu_lic_h': '2. Лицензия',
  'tu_lic_1': 'CleanMenuBar — свободное программное обеспечение, распространяемое по <strong>лицензии MIT</strong>. Вы можете бесплатно использовать, копировать, изменять, распространять и даже продавать его при условии сохранения уведомления об авторских правах и текста лицензии во всех копиях.',
  'tu_lic_2': 'Полный текст сопровождает каждую копию программы и доступен в разделе <strong>О программе → Лицензии</strong>.',
  'tu_lic_3': 'CleanMenuBar происходит от <a href="https://github.com/dwarvesf/hidden">Hidden Bar</a> от Dwarves Foundation, также под лицензией MIT. Их уведомление об авторских правах поставляется вместе с программой.',
  'tu_war_h': '3. Отсутствие гарантий',
  'tu_war_1': 'Программа предоставляется <strong>«как есть»</strong>, без каких-либо гарантий, явных или подразумеваемых, включая, помимо прочего, гарантии товарной пригодности, пригодности для определённой цели и ненарушения прав.',
  'tu_war_2': 'Мы не гарантируем бесперебойной или безошибочной работы программы, а также совместимости с какой-либо конкретной конфигурацией оборудования, версией macOS или сочетанием другого ПО.',
  'tu_lia_h': '4. Ограничение ответственности',
  'tu_lia_1': 'В максимальной степени, допускаемой применимым правом, авторы и правообладатели не несут ответственности по любым искам, убыткам или иным обязательствам, будь то из договора, деликта или иного основания, возникающим из программы или её использования.',
  'tu_lia_2': 'Это включает, помимо прочего, потерю данных, упущенную выгоду, перерыв в деятельности, а также косвенные или сопутствующие убытки.',
  'tu_lia_3': 'Ничто в настоящих Условиях не исключает и не ограничивает ответственность, которая не может быть исключена или ограничена согласно применимому праву Бразилии, включая законодательство о защите прав потребителей.',
  'tu_risk_h': '5. Использование на свой риск',
  'tu_risk_1': 'CleanMenuBar меняет отображение значков в строке меню macOS, используя только публичные API Apple. Тем не менее поведение строки меню может меняться между версиями системы, и обновления macOS могут повлиять на работу программы.',
  'tu_risk_2': 'Вы отвечаете за резервное копирование своих данных и за оценку того, подходит ли программа для ваших задач.',
  'tu_priv_h': '6. Конфиденциальность',
  'tu_priv_1': 'CleanMenuBar не собирает, не передаёт и не хранит удалённо никаких данных.',
  'tu_chg_h': '7. Изменения',
  'tu_chg_1': 'Настоящие Условия могут обновляться. Действующей всегда является редакция, опубликованная на этой странице с указанной выше датой.',
  'tu_law_h': '8. Применимое право',
  'tu_law_1': 'Настоящие Условия регулируются правом Бразилии.',
}
